spring:
  datasource:
    username: ${ROOT:root}
    password: ${ROOT_PASSWORD:1234}
    url: jdbc:mysql://${TICKET_MYSQL_HOST:localhost}:3306/ticket_trove?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      port: ${REDIS_REDIS_PORT:6379}
      host: ${REDIS_REDIS_HOST:127.0.0.1}
    replica:
      port: ${REDIS_REPLICA_PORT:6380}
      host: ${REDIS_REPLICA_HOST:127.0.0.1}
    replica2:
      port: ${REDIS_REPLICA2_PORT:6381}
      host: ${REDIS_REPLICA2_HOST:127.0.0.1}
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret-key: ${JWT_SECRET_KEY:NjRLWTY0cVU3S0NjN0oyMDY0MlU2N2lVN0p5ZzY0dWtDZz09}
server:
  port: ${SERVER_PORT:8001}


